name: First workflow

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Echo phrase for job1
              run: echo "This is job1"
            - name: Echo step is complete for job1
              run: echo "Step for job1 is complete"
    job2:
      runs-on: ubuntu-latest
      steps:
        - name: Echo phrase for job2
          run: echo "This is job2"
        - name: Echo step is complete for job2
          run: echo "Step for job2 is complete"
        - name: Cowsays
          uses: actions/checkout@v2
        - name: Run Cowsays action
          uses: peter-evans/cowsay-action@v2
          with:
            text: "Ready for prod-ship it!"
            color: magenta
